name: terraform-validate
description: Validate a terraform configuration directory
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: true

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions:v1.9.3
  entrypoint: /entrypoints/validate.sh

branding:
  icon: globe
  color: purple
