name: terraform-validate
description: Validate a terraform configuration directory
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the workspace to use for the `terraform.workspace` value while validating.
    required: false
    default: default

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:4fec008558a518785e1ac10e1f601a584d2642a013e871f2c50134f7ed14f361
  entrypoint: /entrypoints/validate.sh

branding:
  icon: globe
  color: purple
