name: terraform-validate
description: Validate a terraform configuration directory
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:40842eb9f7e95f28573f82ebec653c15687f7b5b1c03a7b10e2c1de1d4a68e15
  entrypoint: /entrypoints/validate.sh

branding:
  icon: globe
  color: purple
