name: terraform-validate
description: Validate a terraform configuration directory
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: true

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:4249a9c33cb8c97461daf001145885c17fdde1ba297dbd1d6c11b6f37c3b1eb9
  entrypoint: /entrypoints/validate.sh

branding:
  icon: globe
  color: purple
