name: terraform-validate
description: Validate a terraform configuration directory
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:f5aab4390e96e8211b35c9b6caa903ef692b23d3138b17901c145f0505f0dd22
  entrypoint: /entrypoints/validate.sh

branding:
  icon: globe
  color: purple
